kind: Pod
apiVersion: v1
metadata:
  generateName: bctw-db-1-
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.97.51.86"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.97.51.86"
          ],
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu request for container bctw-db; cpu limit for
      container bctw-db
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: bctw-db
    openshift.io/deployment.name: bctw-db-1
    openshift.io/scc: restricted
  selfLink: /api/v1/namespaces/0dff19-test/pods/bctw-db-1-gztqs
  resourceVersion: '1285723169'
  name: bctw-db-1-gztqs
  uid: ade09af8-7b05-4f69-b0e6-05fb94dba922
  creationTimestamp: '2021-07-04T22:20:13Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-07-04T22:20:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/deployment-config.latest-version': {}
            'f:openshift.io/deployment-config.name': {}
            'f:openshift.io/deployment.name': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deployment': {}
            'f:deploymentconfig': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"28ad016f-e1c1-4be5-b8e7-3e1b2e7c65e7"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"bctw-db"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/var/lib/pgsql/data"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources':
                .: {}
                'f:limits':
                  .: {}
                  'f:memory': {}
                'f:requests':
                  .: {}
                  'f:memory': {}
              'f:env':
                .: {}
                'k:{"name":"POSTGRESQL_DATABASE"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"POSTGRESQL_PASSWORD"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:secretKeyRef':
                      .: {}
                      'f:key': {}
                      'f:name': {}
                'k:{"name":"POSTGRESQL_USER"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:secretKeyRef':
                      .: {}
                      'f:key': {}
                      'f:name': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":5432,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"volume-qvg1l"}':
              .: {}
              'f:name': {}
              'f:persistentVolumeClaim':
                .: {}
                'f:claimName': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2021-07-05T20:40:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2021-07-05T20:41:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.97.51.86"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
  namespace: 0dff19-test
  ownerReferences:
    - apiVersion: v1
      kind: ReplicationController
      name: bctw-db-1
      uid: 28ad016f-e1c1-4be5-b8e7-3e1b2e7c65e7
      controller: true
      blockOwnerDeletion: true
  labels:
    app: bctw-db
    deployment: bctw-db-1
    deploymentconfig: bctw-db
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-wv6g8
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: mcs-silver-app-40.dmz
  securityContext:
    seLinuxOptions:
      level: 's0:c76,c70'
    fsGroup: 1005840000
  containers:
    - resources:
        limits:
          cpu: 250m
          memory: 2Gi
        requests:
          cpu: 50m
          memory: 1Gi
      terminationMessagePath: /dev/termination-log
      name: bctw-db
      env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bctw
              key: password
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: bctw
              key: username
        - name: POSTGRESQL_DATABASE
          value: bctw
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1005840000
      ports:
        - containerPort: 5432
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: volume-qvg1l
          mountPath: /var/lib/pgsql/data
        - name: default-token-p887k
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/0dff19-tools/postgres-postgis@sha256:720b6ade23b8d25a6280494eeea5e786813761bd1a92214d89e8a5843962f050
  serviceAccount: default
  volumes:
    - name: volume-qvg1l
      persistentVolumeClaim:
        claimName: bctw-data
    - name: default-token-p887k
      secret:
        secretName: default-token-p887k
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-07-04T22:20:13Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-07-05T20:41:14Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-07-05T20:41:14Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-07-04T22:20:13Z'
  hostIP: 142.34.151.161
  podIP: 10.97.51.86
  podIPs:
    - ip: 10.97.51.86
  startTime: '2021-07-04T22:20:13Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: bctw-db
      state:
        running:
          startedAt: '2021-07-05T20:41:13Z'
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/0dff19-tools/postgres-postgis@sha256:720b6ade23b8d25a6280494eeea5e786813761bd1a92214d89e8a5843962f050
      image: >-
        image-registry.openshift-image-registry.svc:5000/0dff19-tools/postgres-postgis@sha256:720b6ade23b8d25a6280494eeea5e786813761bd1a92214d89e8a5843962f050
      lastState: {}
      containerID: 'cri-o://55b0d92945d167c2ad3a64dabf3d5e1adb2b4072d8b56dd6bbcec336c95f8d39'
  qosClass: Burstable
